version: 2
jobs: 
 build:
   docker: 
     - image: circleci/python:3.6.2-stretch-browsers
        envrionment: 
           FLASK_CONFIG: testing
           TEST_DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
     - image: circleci/postgres:9.6.5-alpine-ram
        envrionment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
   steps:
     - checkout
     - run: mkdir test-reports
     - run: 
         name: Download Selenium
         command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
     - run:
         name: Start Selenium
         command: | 
           java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
         background: true
     
     - restore_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
     - run: 
         name: Install Python deps in venv
         command: |
           python3 -m venv venv . venv/bin/activate
           pip install -r requirements/dev.txt
     - save_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
         paths:
           - "venv"
     - run:
         command: |
          . venv/bin/activate
          python manage.py test
     - store_artifacts:
         path: test-reports/
         destination: tr1
     - store_test_result:
         path: test-reports
 deploy:
   steps:
     - checkout
     - run: 
        name: Deploy Master to Heroku 
        command: | 
             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
